#ifndef PELCOD_DEFS_H
#define PELCOD_DEFS_H

/* standard commands */
#define PELCOD_STD_SENSE
#define PELCOD_STD_LEFT
#define PELCOD_STD_RIGHT
#define PELCOD_STD_UP
#define PELCOD_STD_DOWN
#define PELCOD_STD_ZOOM_TELE
#define PELCOD_STD_ZOOM_WIDE
#define PELCOD_STD_FOC_FAR
#define PELCOD_STD_FOC_NEAR
#define PELCOD_STD_IRIS_CLOSE
#define PELCOD_STD_IRIS_OPEN
#define PELCOD_STD_CAM_ON
#define PELCOD_STD_CAM_OFF

/* extended commands */
#define PELCOD_EXT_PRE_SET
#define PELCOD_EXT_PRE_CLR
#define PELCOD_EXT_PRE_TO
#define PELCOD_EXT_FLIP
#define PELCOD_EXT_AUX_SET
#define PELCOD_EXT_AUX_CLR
#define PELCOD_EXT_RST
#define PELCOD_EXT_ZON_START
#define PELCOD_EXT_ZON_END
#define PELCOD_EXT_ZON_SCAN
#define PELCOD_EXT_ZON_STOP
#define PELCOD_EXT_CHAR_WR
#define PELCOD_EXT_SCR_CLR
#define PELCOD_EXT_ALARM_ACK
#define PELCOD_EXT_SPATT_START
#define PELCOD_EXT_SPATT_STOP
#define PELCOD_EXT_PATT_RUN
#define PELCOD_EXT_
#define PELCOD_EXT_
#define PELCOD_EXT_
#define PELCOD_EXT_
#define PELCOD_EXT_
#define PELCOD_EXT_
#define PELCOD_EXT_

#endif // PELCOD_DEFS_H
